# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Cloudtype Github Actions - Connect Repository
      uses: cloudtype-github-actions/connect@v1
      with:
        token: ${{ secrets.CLOUDTYPE_TOKEN }}
        ghtoken: ${{ secrets.GHP_TOKEN }}
    - name: Cloudtype Github Actions - Deploy
      uses: cloudtype-github-actions/deploy@v1
      with:
        token: ${{ secrets.CLOUDTYPE_TOKEN }}
        project: zer0ken_the_developer/kenken-3rd
        yaml: |
          name: flask
          app: python@3.10
          options:
            env:
              - name: BOT_TOKEN
                var: ${{ secrets.BOT_TOKEN }}
            ports: 8000
            start: python ./
          context:
            git:
              url: git@github.com:${{ github.repository }}.git
              ref: ${{ github.ref }}
            preset: python-flask
